package fi.wessmaker.fanwipcsoftware.communication;

public enum ReguestType {
	REGUEST_SPEED_VALUE,
	REGUEST_SPINNING_STATUS,
	REGUEST_TEMPERATURE_VALUE,
	REGUEST_OFFSET_VALUE,
	REGUEST_PWM_VALUE,
	REGUEST_IDLE_TIME,
	REGUEST_DEVICE_ONTIME,
	REGUEST_CONNECTION_TIME,
	REGUEST_SPIN_COUNT
}
